sudo: required
services:
  - docker
language: generic

before_install:
  - docker build -t takayone/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true takayone/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-499041746093"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
